apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3
  template:
    spec:
      containers:
        - image: ubuntu
          name: math-job
          command: ['expr', '3', '+', '2']
      restartPolicy: Never