apiVersion: v1
kind: Pod
metadata:
  name: MYAPP-POD
spec:
  containers:
    - name: data-processor
      image: data-processor
  
  affinity:
    nodeAffinity:
      requireDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: in
              values:
                - Large
                

