apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper  
      imagePullPolicy: Never
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: app-config-ubuntu
