apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata: 
      name: my-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - name: my-app-pod
          image: nginx
  replicas: 3

