apiVersion: v1
kind: pod
metadata:
  name: myapp-prod
spec:
  containers:
    - name: nginx-container
      image: nginx

  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"